# This is a basic workflow that is manually triggered

name: "Pub Step 2: Publish to Marketplace"

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    inputs:
      ref:
        description: The release TAG to publish. i.e. `v2.2.2`
        required: true
        default: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.ref }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn test
      - name: Build Extension .vsix
        run: yarn run package-extension
      - name: Publish VSCE
        run: find ./build -name "*.vsix" | xargs npx vsce publish -p ${{ secrets.VSCE_TOKEN }} --packagePath || echo "::warning title=VSCE::Failed to Publish to VS Code Marketplace."
      - name: Publish OVSX
        run: find ./build -name "*.vsix" | xargs npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}  || echo "::warning title=OVSX::Failed to Publish to Eclipse Open VSX."
# cspell:ignore vsix xargs OVSX
